

services:

  postgres:
    image: postgres:16
    container_name: healthcare-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: healthcare
      POSTGRES_PASSWORD: healthcare123
      POSTGRES_DB: healthcare_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthcare -d healthcare_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: healthcare-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:5000"
    env_file:
      - backend/.env
    

  frontend:
    build: ./frontend
    container_name: healthcare-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"

volumes:
  postgres_data:
 