
name: Deploy to ECS

on:

  workflow_run:
    workflows:
      - Backend CI
      - Frontend CI
      - Terraform Infrastructure

    types:
      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build -t healthcare-backend ./backend

      - name: Build Frontend Image
        run: |
          docker build -t healthcare-frontend ./frontend

      - name: Tag Backend Image
        run: |
          docker tag healthcare-backend:latest \
          ${{ secrets.ECR_BACKEND_REPOSITORY }}:latest

      - name: Tag Frontend Image
        run: |
          docker tag healthcare-frontend:latest \
          ${{ secrets.ECR_FRONTEND_REPOSITORY }}:latest

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.ECR_BACKEND_REPOSITORY }}:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.ECR_FRONTEND_REPOSITORY }}:latest

      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.BACKEND_SERVICE }} \
            --force-new-deployment

          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.FRONTEND_SERVICE }} \
            --force-new-deployment