name: Terraform Infrastructure

on:

  push:
    branches:
      - main
    paths:
      - "terraform/**"

  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

concurrency:
  group: terraform
  cancel-in-progress: true

jobs:

  deploy-dev:

    uses: ./.github/workflows/terraform-deploy.yml

    with:
      environment: dev
      backend_config: backend/backend-dev.hcl
      tfvars_file: environments/dev.tfvars

    secrets: inherit

  deploy-staging:

    needs: deploy-dev

    uses: ./.github/workflows/terraform-deploy.yml

    with:
      environment: staging
      backend_config: backend/backend-staging.hcl
      tfvars_file: environments/staging.tfvars

    secrets: inherit

  deploy-production:

    needs: deploy-staging

    uses: ./.github/workflows/terraform-deploy.yml

    with:
      environment: production
      backend_config: backend/backend-prod.hcl
      tfvars_file: environments/prod.tfvars

    secrets: inherit                        