 name: Terraform Infrastructure

 on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Select environment to deploy"
        required: true
        default: "prod"
        type: choice
        options:
          - prod

 concurrency:
  group: terraform-${{ github.event.inputs.target_env }}
  cancel-in-progress: false

 jobs:
  deploy-prod:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: prod
    secrets: inherit