name: Reusable Terraform Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      backend_config:
        required: true
        type: string

      tfvars_file:
        required: true
        type: string

jobs:

  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    env:
      AWS_ACCOUNT_ID: "245758552830"

    steps:

      # ==================================================
      # CHECKOUT
      # ==================================================

      - name: Checkout
        uses: actions/checkout@v4


      # ==================================================
      # TERRAFORM
      # ==================================================

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -reconfigure \
            -backend-config="${{ inputs.backend_config }}"

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_secret_key: ${{ secrets.TF_VAR_secret_key }}
        run: |
          terraform plan \
            -lock-timeout=30s \
            -input=false \
            -no-color \
            -var-file="${{ inputs.tfvars_file }}"

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_secret_key: ${{ secrets.TF_VAR_secret_key }}
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            -var-file="${{ inputs.tfvars_file }}"


      # ==================================================
      # ECR LOGIN
      # ==================================================

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      # ==================================================
      # IMAGE TAG
      # ==================================================

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"


      # ==================================================
      # BUILD BACKEND
      # ==================================================

      - name: Build Backend Image
        run: |
          docker build \
            -t healthcare-backend:${GITHUB_SHA} \
            -t healthcare-backend:latest \
            ./backend


      # ==================================================
      # BUILD FRONTEND
      # ==================================================

      - name: Build Frontend Image
        run: |
          docker build \
            -t healthcare-frontend:${GITHUB_SHA} \
            -t healthcare-frontend:latest \
            ./frontend


      # ==================================================
      # TAG BACKEND
      # ==================================================

      - name: Tag Backend Image
        run: |
          docker tag healthcare-backend:${GITHUB_SHA} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-backend:${IMAGE_TAG}

          docker tag healthcare-backend:${GITHUB_SHA} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-backend:latest


      # ==================================================
      # TAG FRONTEND
      # ==================================================

      - name: Tag Frontend Image
        run: |
          docker tag healthcare-frontend:${GITHUB_SHA} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-frontend:${IMAGE_TAG}

          docker tag healthcare-frontend:${GITHUB_SHA} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-frontend:latest


      # ==================================================
      # PUSH BACKEND
      # ==================================================

      - name: Push Backend Image
        run: |
          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-backend:${IMAGE_TAG}

          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-backend:latest


      # ==================================================
      # PUSH FRONTEND
      # ==================================================

      - name: Push Frontend Image
        run: |
          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-frontend:${IMAGE_TAG}

          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/healthcare-${{ inputs.environment }}-frontend:latest


      # ==================================================
      # ECS BACKEND
      # ==================================================

      - name: Deploy Backend
        run: |
          aws ecs update-service \
            --cluster healthcare-${{ inputs.environment }} \
            --service healthcare-backend \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}


      # ==================================================
      # ECS FRONTEND
      # ==================================================

      - name: Deploy Frontend
        run: |
          aws ecs update-service \
            --cluster healthcare-${{ inputs.environment }} \
            --service healthcare-frontend \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}


      # ==================================================
      # WAIT BACKEND
      # ==================================================

      - name: Wait for Backend
        run: |
          aws ecs wait services-stable \
            --cluster healthcare-${{ inputs.environment }} \
            --services healthcare-backend \
            --region ${{ secrets.AWS_REGION }}


      # ==================================================
      # WAIT FRONTEND
      # ==================================================

      - name: Wait for Frontend
        run: |
          aws ecs wait services-stable \
            --cluster healthcare-${{ inputs.environment }} \
            --services healthcare-frontend \
            --region ${{ secrets.AWS_REGION }}